### ISSUE TITLE
Siorava Card Bonus LUK Discrepancy

### ISSUE THREAD

**Issue by bl-ehhh** [kutsuru/ttcalculator#6]
Siorava Card, despite being equipped in a slotted middle headgear, seems to acquire the refinement on the upper headgear instead and then adding the respective bonus LUK. I am not sure if it is intended in-game and in the calculator but I expected it to just give the base bonus due to slotted middle headgears being unable to be refined.

> #4530: Siorava_Card
> 
> LUK +2
> [Merchant and Merchant Upper Classes]
> Every 3 refine on the compounded item adds LUK +1.
> 
> `bonus bLuk,2; if(BaseClass==Job_Merchant){ bonus bLuk,getrefine()/3; }`

**Comment by kutsuru** [comment]
Same issue with :
- Angra Mantis
- Dolomedes
- Cendrawasih
- King Dramoh
