### ISSUE TITLE
Missing Gears

### ISSUE THREAD

**Issue by bl-ehhh** [kutsuru/ttcalculator#9]
Upper Headgear
- [x] Drooping Domovoi [1] [18628]

Accessories (Stat Gloves equippable for extended class now as per previous update)
- [x] AGI Glove [2919]
- [x] AGI Glove [1] [2925]
- [x] DEX Glove [2921]
- [x] DEX Glove [1] [2927]
- [x] INT Glove [2918]
- [x] INT Glove [1] [2924]
- [x] LUK Glove [2922]
- [x] LUK Glove [1] [2928]
- [x] STR Glove [2917]
- [x] STR Glove [1] [2923]
- [x] VIT Glove [2920]
- [x] VIT Glove [1] [2926]

**Comment by kutsuru** [comment]
Drooping Domovoi has been there for a really long time already.
Stat gloves are not equip-able by extended classes with following commit 5156f022ccf57de61b17377947e871797c6a4be5
